### ISSUE TITLE
open

### ISSUE THREAD

**Issue by amin9565** [adityak368/FileBrowser#12]
hello and thank you for good lib.
i want to open audio file  when FileBrowser  lunched but when click on audio file close FileBrowser and no things !
what do i do ?

**Comment by adityak368** [comment]
If you want to select a file, you will need to use filechooser class
If you just need file browsing, then use filebrowser class

Ex:

Intent i2 = new Intent(getApplicationContext(), FileChooser.class);
i2.putExtra(Constants.SELECTION_MODE,Constants.SELECTION_MODES.SINGLE_SELECTION.ordinal());
startActivityForResult(i2,PICK_FILE_REQUEST);

To get the selected file, In your calling activity's onActivityResult
method, use the following

if (requestCode == PICK_FILE_REQUEST && data!=null) {
      if (resultCode == RESULT_OK) {
          Uri file = data.getData();
      }
}

**Comment by amin9565** [comment]
thank you but this code dose not work .
when click audio file it does not happen!

**Comment by adityak368** [comment]
Not sure i can help here. Maybe u can share the snippet and we can see

**Comment by amin9565** [comment]
i want to play audio with default player when click file in FileBrowser .
now when click file just save path in Uri file .
what do i do ?
thanks alot

**Comment by adityak368** [comment]
to play audio, you would need to use the FileBrowser class as described in the readme. 
Please use the latest version (1.8). It should work now
