### ISSUE TITLE
After applying filter for displaying only specific files, it's still showing files without extensions

### ISSUE THREAD

**Issue by kinjalravel** [adityak368/FileBrowser#13]
Hi @adityak368,

Great library :)

**What am I trying to do?**
I want to display only excel files 

**What is displaying right now?**
No matters which filter  you set, it always shows files that don't have any extentions 

![image](https://user-images.githubusercontent.com/41296632/47170368-741a5900-d323-11e8-99f3-05f33fcb5337.png)

I have applied filters as per documentation in readme file 
````java
Intent i = new Intent(this, FileBrowser.class); //works for all 3 main classes (i.e FileBrowser, FileChooser, FileBrowserWithCustomHandler)
i.putExtra(Constants.ALLOWED_FILE_EXTENSIONS, "xls;xlsx");

**Comment by kinjalravel** [comment]
Does removing check fileExtension.isEmpty()? will fix this issue, I am not 100% sure 

https://github.com/adityak368/Android-FileBrowser-FilePicker/blob/master/filebrowser/src/main/java/com/aditya/filebrowser/fileoperations/FileNavigator.java#L39

**Comment by kinjalravel** [comment]
@adityak368,

I have resolved the issue, please do let me know if you required PR

**Comment by kinjalravel** [comment]
@adityak368 ,

I have resolved the issue, please do let me know if you want a PR.

**Comment by adityak368** [comment]
Thanks for resolving the issue. Can you please raise a PR?
