### ISSUE TITLE
Problem in Gradle 

### ISSUE THREAD

**Issue by oduysmara** [adityak368/FileBrowser#2]
Error:(81, 13) Failed to resolve: com.adityak:browsemyfiles:1.2
<a href="openFile:/Users/oduy/Downloads/mename-mobile-new version/MenaMe/build.gradle">Show in File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>

**Comment by adityak368** [comment]
Hi,

I checked the issue, and i am able to add the library to the project using
compile 'com.adityak:browsemyfiles:1.2'.

Make sure that offline mode is disabled. Also make sure that you have proper internet connection. (please check proxy settings if applicable)

Thanks
Aditya K

**Comment by adityak368** [comment]
Cannot be reproduced. Please check v1.4
