### ISSUE TITLE
How to filter file types?

### ISSUE THREAD

**Issue by ismaiI1** [adityak368/FileBrowser#3]
How can I list just the file types I want?

**Comment by adityak368** [comment]
Hi,

Currently this feature is not implemented. You can only filter by files or folders. I will make the changes when i release the next version (v1,3) very soon. If you want the feature immediately, you can take a fork and change the code and also if you have the time, you can also make the changes and contribute to the repository

Thanks
Aditya K

**Comment by ismaiI1** [comment]
I will wait your new version :) thanks..

**Comment by adityak368** [comment]
I have updated the version to v1.3. I have added a searchbar for filtering in current directory

**Comment by adityak368** [comment]
Fixed in version > 1.3 via searchbar
