### ISSUE TITLE
exceeding dex limit

### ISSUE THREAD

**Issue by dreasn** [adityak368/FileBrowser#5]
I got exeeding dex limit:

Error:Error converting bytecode to dex:
Cause: com.android.dex.DexIndexOverflowException: Cannot merge new index 66596 into a non-jumbo instruction!

**Comment by adityak368** [comment]
Can you please share more details?
In the meantime can you try to fix it using this thread?
[(http://stackoverflow.com/questions/26093664/android-studio-only-dexexception-cannot-merge-new-index-65536-into-a-non-jumbo)]
Please let me know if it still exists

**Comment by dreasn** [comment]
I tried using multiDexEnabled: 
https://developer.android.com/studio/build/multidex.html
It builds apk successfully now. Thanks.

Note: The previous error arrised when I 'Build Apk' (from Android Studio). However if I just 'run app (Shift F10)' it will be compiled alright even without multidex enabled.
