### ISSUE TITLE
colorPrimary not working?

### ISSUE THREAD

**Issue by haerulmuttaqin** [adityak368/FileBrowser#9]
<item name="colorPrimary">@color/primaryColor</item>

**Comment by adityak368** [comment]
Sorry for the late reply! I was kinda busy lately and did not have much time maintaining it. let me look into it

**Comment by EarlyWild** [comment]
I also cannot get the primary color to change

**Comment by adityak368** [comment]
Please add the following to your app's res/values/colors.xml. Tested and working. Closing the issue. Let me know if you still face any issues

```
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <color name="colorPrimary">#3F51B5</color>
    <color name="colorPrimaryDark">#2196F3</color>
    <color name="colorAccent">#FF4081</color>
</resources>
```

**Comment by haerulmuttaqin** [comment]
Thank you 👍
